// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-ZXAqsogCrMuGzcwVRGPWGyDh87GHKc',
    appId: '1:1011079266149:web:5ab8615ab03b8ccbd7eb8c',
    messagingSenderId: '1011079266149',
    projectId: 'chat-ac9f8',
    authDomain: 'chat-ac9f8.firebaseapp.com',
    storageBucket: 'chat-ac9f8.appspot.com',
    measurementId: 'G-FC7706D60S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxjLDJ0S-OwtEhqf58Xxpe41nd6Qgd1Jo',
    appId: '1:1011079266149:android:762fae41b9baeb10d7eb8c',
    messagingSenderId: '1011079266149',
    projectId: 'chat-ac9f8',
    storageBucket: 'chat-ac9f8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz-ZXAqsogCrMuGzcwVRGPWGyDh87GHKc',
    appId: '1:1011079266149:web:8f13fc29f5a61b58d7eb8c',
    messagingSenderId: '1011079266149',
    projectId: 'chat-ac9f8',
    authDomain: 'chat-ac9f8.firebaseapp.com',
    storageBucket: 'chat-ac9f8.appspot.com',
    measurementId: 'G-8RRJ9DJ3VV',
  );
}
